# Generated by Django 5.0.6 on 2024-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
